//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirDepR2.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.HoraSalons = new HashSet<HoraSalon>();
            this.PuntosExtras = new HashSet<PuntosExtra>();
        }
    
        public int ID { get; set; }
        public int IDMateria { get; set; }
        public Nullable<int> IDProfesor { get; set; }
        public Nullable<int> CRN { get; set; }
        public string Periodo { get; set; }
        public short Cupo { get; set; }
        public Nullable<short> Inscritos { get; set; }
        public short Grupo { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Profesor Profesor { get; set; }
        public virtual ICollection<HoraSalon> HoraSalons { get; set; }
        public virtual ICollection<PuntosExtra> PuntosExtras { get; set; }
    }
}
