//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirDepR2.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoraSalon
    {
        public int ID { get; set; }
        public int IDCurso { get; set; }
        public int IDSalon { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public string Dia { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
