//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirDepR2.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public Materia()
        {
            this.Cursoes = new HashSet<Curso>();
        }
    
        public int ID { get; set; }
        public string ClaveMateria { get; set; }
        public string Nombre { get; set; }
        public short Unidades { get; set; }
        public Nullable<bool> Lab { get; set; }
        public string Nivel { get; set; }
    
        public virtual ICollection<Curso> Cursoes { get; set; }
    }
}
