//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirDepR2.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbContext : DbContext
    {
        public dbContext()
            : base("name=dbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<Curso> Cursoes { get; set; }
        public virtual DbSet<HoraSalon> HoraSalons { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<PuntosExtra> PuntosExtras { get; set; }
        public virtual DbSet<Salon> Salons { get; set; }
    
        public virtual ObjectResult<RegresaPuntosExtras_Result> RegresaPuntosExtras(string nomina)
        {
            var nominaParameter = nomina != null ?
                new ObjectParameter("Nomina", nomina) :
                new ObjectParameter("Nomina", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RegresaPuntosExtras_Result>("RegresaPuntosExtras", nominaParameter);
        }
    
        public virtual ObjectResult<RegresaHorarioProfesor_Result> RegresaHorarioProfesor(string nomina)
        {
            var nominaParameter = nomina != null ?
                new ObjectParameter("Nomina", nomina) :
                new ObjectParameter("Nomina", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RegresaHorarioProfesor_Result>("RegresaHorarioProfesor", nominaParameter);
        }
    }
}
