//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DirDepR2.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Profesor
    {
        public Profesor()
        {
            this.Cursoes = new HashSet<Curso>();
        }

        [HiddenInput(DisplayValue=false)]
        public int ID { get; set; }
        
        [Display(Name="Nómina")]
        public string Nomina { get; set; }
        
        public string Nombre { get; set; }
        
        [StringLength(50)]
        [Display(Name="Apellido Paterno")]
        public string ApellidoPaterno { get; set; }

        [StringLength(50)]
        [Display(Name = "Apellido Materno")]
        public string ApellidoMaterno { get; set; }

        [Display(Name = "Correo electrónico")]
        public string Correo { get; set; }
        public string Departamento { get; set; }
    
        public virtual ICollection<Curso> Cursoes { get; set; }
    }
}
