//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirDepR2.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntosExtra
    {
        public int ID { get; set; }
        public int IDAlumno { get; set; }
        public Nullable<int> IDCurso { get; set; }
        public string Ponderacion { get; set; }
        public string Descripción { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
