//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirDepR2.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salon
    {
        public Salon()
        {
            this.HoraSalons = new HashSet<HoraSalon>();
        }
    
        public int ID { get; set; }
        public string NumeroSalon { get; set; }
        public short Capacidad { get; set; }
        public string Edificio { get; set; }
    
        public virtual ICollection<HoraSalon> HoraSalons { get; set; }
    }
}
